sorted-list: main.o sorted-list.o
    gcc -o sorted-list main.o sorted-list.o

main.o: main.c sorted-list.h
    gcc -c main.c

sorted-list.o: sorted-list.c sorted-list.h
    gcc -c sorted-list.c

clean: 
	rm -rf sorted-list main.o sorted-list.o
